def get_player_playtime_hours():
    return [
        "Marc",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
        "Joaquim",
        "Arnau",
    ], [10, 20, 30, 20, 30, 20, 30, 20, 30, 20, 30, 20, 30, 20, 30, 20, 30]
